### PR TITLE
decode without length table

### PR DESCRIPTION
**Pull request by KWillets**
This works on clang-4.0, but the pextrb intrinsic throws errors on gcc:

/usr/lib/gcc/x86_64-linux-gnu/6/include/smmintrin.h:443:27: error: selector must be an integer constant in the range 0..15
    return (unsigned char) __builtin_ia32_vec_ext_v16qi ((__v16qi)__X, __N);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I believe this is simply wrong, as the arg is a const int, but not a constant.  

Performance on clang is *exactly* the same:  

kendall@skylake:~/streamvbyte$ ./perf
time = 0.036000  1388888960.000000 uints/sec
compsize=1281422 compsize2 = 1281422
Compressed 500000 integers down to 1281422 bytes.

### CODE REVIEW

**Comment by lemire** [comment]
It is great that you tested this. I don't expect huge performance differences... but if we could get the same performance with simpler code... that'd be a win.

> I believe this is simply wrong, as the arg is a const int, but not a constant.

What is "this" in "this is simply wrong"?

Ok. So here I think that the difference has to do with how the intrinsics get compiled. The intel specs says that ``_mm_extract_epi8``  gets compiled to ``pextrb``. But that's not what clang does in this specific case.  What clang does is to store the vector register (``vmov``) and then load back the part needed (with ``mov``). [You can check the compiler output online](https://godbolt.org/g/eNYF4e).

So it is the case that clang offers are more general ``_mm_extract_epi8`` intrinsic, one that can take immediate values and also variables.

I am not sure that anything is wrong, except maybe for the fact that clang does not follow the Intel specification. But whether clang is wrong looks like something from the realm of bikeshedding. I think that they do something reasonable.


Still, the produced code in our case does not seem optimal. We might as well bypass the vector register and go right at the location in ``shuffleTable``. That would have the benefit of being portable! It sounds entirely too silly to load the data in a vector register, save the vector register, then reload the part we need in a scalar register.

**Comment by KWillets** [comment]
Yes, another route might work.  My thought was that the register extract would be faster, but I didn't research it.  

The intel ref says the arg is const int, but pextrb says it's imm8, which I think means constant.

**Comment by lemire** [comment]
I think it needs to be an immediate, that is a compile-time constant.

**Comment by KWillets** [comment]
I just pushed array fetching; it's the same perf on clang-4.0 (haven't check gcc vs. master) and builds on gcc.

**Comment by lemire** [comment]
I'll merge but disable by default because I am concerned that there are possible performance considerations.
